#!/bin/bash
set -evx

# uninstall systemd service
sudo systemctl stop mongodb.service
sudo systemctl disable mongodb.service
sudo rm -f /etc/systemd/system/mongodb.service

# remove utils
sudo rm -rf utils/*.exp
cd utils/
for name in * ; do
    echo "Removing /usr/sbin/$name from the system ..."
    sudo rm -f /usr/sbin/$name
done;
cd ../